Repository CS5500-Team5/Tuiter-Node-Server, pull requests merged in 2022-04, with the labels that each got.

#1 TUITER-28 Adding Poll DAOs and APIs
  controllers/PollController.ts
  daos/PollDao.ts
  daos/TuitDao.ts
  interfaces/PollControllerI.ts
  interfaces/PollDaoI.ts
  interfaces/TuitDaoI.ts
  interfaces/VoteDaoI.ts
  models/polls/PollOption.ts
  models/polls/PollStats.ts
  models/tuits/Tuit.ts
  models/votes/Vote.ts
  mongoose/polls/PollOptionModel.ts
  mongoose/polls/PollOptionSchema.ts
  mongoose/polls/PollStatsModel.ts
  mongoose/polls/PollStatsSchema.ts
  mongoose/tuits/TuitSchema.ts
  server.ts
Labels: enhancement

#3 TUITER-51: update numvotes on vote creation/deletion
  controllers/VoteController.ts
  daos/VoteDao.ts
  interfaces/VoteDaoI.ts
Labels: enhancement

#4 TUITER-51: added session to vote controller
  controllers/VoteController.ts
Labels: enhancement

#6 TUITER-59 Test APIs for Polls and Votes
  controllers/TuitController.ts
  controllers/VoteController.ts
  daos/PollDao.ts
  daos/TuitDao.ts
Labels: bug, enhancement

#8 TUITER-78: added votes documentation
  controllers/VoteController.ts
  daos/VoteDao.ts
  models/users/User.ts
  models/votes/Vote.ts
  mongoose/tuits/TuitSchema.ts
  mongoose/votes/VoteModel.ts
  mongoose/votes/VoteSchema.ts
Labels: documentation

#9 TUITER-78: added documentation for node project
  controllers/AuthenticationController.ts
  controllers/SessionController.ts
  daos/LikeDao.ts
  models/polls/PollOption.ts
  models/polls/PollStats.ts
  models/tuits/Stats.ts
  models/tuits/Tuit.ts
  models/users/AccountType.ts
  models/users/Location.ts
  models/users/MaritalStatus.ts
  mongoose/dislikes/DislikeSchema.ts
  mongoose/likes/LikeSchema.ts
  mongoose/polls/PollOptionSchema.ts
  mongoose/polls/PollStatsSchema.ts
  mongoose/users/UserSchema.ts
Labels: documentation
